### ISSUE TITLE
jcenter is being shutdown

### ISSUE THREAD

**Issue by rivercartwright** [babylonhealth/certificate-transparency-android#79] opened 2021-02-24 00:45 UTC
If I read this article correctly I believe it means jcenter is going away.

"sunsetting Bintray (including JCenter), GoCenter, and ChartCenter services on May 1st, 2021."

https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

Would you consider publishing to maven central or another suitable repository?

**Comment by mattmook** [comment] 2021-02-24 00:52
Closing as duplicate of #77

**Closed** 2021-02-24 00:52 UTC
