### ISSUE TITLE
JCenter deprecation

### ISSUE THREAD

**Issue by barnhill** [babylonhealth/certificate-transparency-android#78] opened 2021-02-23 15:13 UTC
Starting from May 1, 2021 JCenter will stop accepting updates as its being sunsetted.

The artifacts for this project should be deployed to an alternate repository such as MavenCentral.

Thanks!

**Comment by mattmook** [comment] 2021-02-23 15:30
Closing as duplicate of #77

**Closed by mattmook** 2021-02-23 15:30 UTC
