### ISSUE TITLE
Sun setting on JCenter 

### ISSUE THREAD

**Issue by saran2020** [babylonhealth/certificate-transparency-android#80] opened 2021-03-12 11:38 UTC
Sun setting on JCenter on `March 31st 2021`. The distribution of the library will have to be down via Maven Central.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by mattmook** [comment] 2021-03-23 19:26
Duplicate of #77

**Closed** 2021-03-23 19:26 UTC
